<?php declare(strict_types=1);

/**
 * Copyright (C) BaseCode Oy - All Rights Reserved
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use BaseCodeOy\Traktor\Links\Actions\GenerateTrackingLink;

it('can generate tracking link', function (
    string $carrier_code,
    string $service_code,
    string $language,
): void {
    expect(
        (new GenerateTrackingLink())->execute(
            carrier_code: $carrier_code,
            service_code: $service_code,
            trackingCode: 'TRACKING_CODE',
            lang: $language,
        ),
    )->toMatchSnapshot();
})->with([
    ['bcmse', 'bcmse', 'en'],
    ['bcmse', 'bcmse', 'fi'],
    ['bcmse', 'bcmse', 'sv'],
    ['cg', 'cg', 'en'],
    ['cg', 'cg', 'fi'],
    ['cg', 'cg', 'sv'],
    ['dhlfreightfi', 'dhlfreightfi', 'en'],
    ['dhlfreightfi', 'dhlfreightfi', 'fi'],
    ['dhlfreightfi', 'dhlfreightfi', 'sv'],
    ['dhlroad', 'dhlroad', 'en'],
    ['dhlroad', 'dhlroad', 'fi'],
    ['dhlroad', 'dhlroad', 'sv'],
    ['dhlroad', 'dhlroad.aspo', 'en'],
    ['dhlroad', 'dhlroad.aspo', 'fi'],
    ['dhlroad', 'dhlroad.aspo', 'sv'],
    ['dhlroad', 'dhlroad.aspor', 'en'],
    ['dhlroad', 'dhlroad.aspor', 'fi'],
    ['dhlroad', 'dhlroad.aspor', 'sv'],
    ['dpd', 'dpd', 'en'],
    ['dpd', 'dpd', 'fi'],
    ['dpd', 'dpd', 'sv'],
    ['fedex', 'fedex', 'en'],
    ['fedex', 'fedex', 'fi'],
    ['fedex', 'fedex', 'sv'],
    ['glsfi', 'glsfi', 'en'],
    ['glsfi', 'glsfi', 'fi'],
    ['glsfi', 'glsfi', 'sv'],
    ['itellalog', 'itellalog', 'en'],
    ['itellalog', 'itellalog', 'fi'],
    ['itellalog', 'itellalog', 'sv'],
    ['jakeluyhtio_suomi', 'jakeluyhtio_suomi', 'en'],
    ['jakeluyhtio_suomi', 'jakeluyhtio_suomi', 'fi'],
    ['jakeluyhtio_suomi', 'jakeluyhtio_suomi', 'sv'],
    ['kl', 'kl', 'en'],
    ['kl', 'kl', 'fi'],
    ['kl', 'kl', 'sv'],
    ['mh', 'mh', 'en'],
    ['mh', 'mh', 'fi'],
    ['mh', 'mh', 'sv'],
    ['netlux', 'netlux', 'en'],
    ['netlux', 'netlux', 'fi'],
    ['netlux', 'netlux', 'sv'],
    ['omni', 'omni', 'en'],
    ['omni', 'omni', 'fi'],
    ['omni', 'omni', 'sv'],
    ['pbrev', 'pbrev', 'en'],
    ['pbrev', 'pbrev', 'fi'],
    ['pbrev', 'pbrev', 'sv'],
    ['plab', 'plab', 'en'],
    ['plab', 'plab', 'fi'],
    ['plab', 'plab', 'sv'],
    ['plscm', 'plscm', 'en'],
    ['plscm', 'plscm', 'fi'],
    ['plscm', 'plscm', 'sv'],
    ['pnl', 'pnl', 'en'],
    ['pnl', 'pnl', 'fi'],
    ['pnl', 'pnl', 'sv'],
    ['posti', 'posti', 'en'],
    ['posti', 'posti', 'fi'],
    ['posti', 'posti', 'sv'],
    ['postnord', 'postnord', 'en'],
    ['postnord', 'postnord', 'fi'],
    ['postnord', 'postnord', 'sv'],
    ['sbtl', 'sbtl', 'en'],
    ['sbtl', 'sbtl', 'fi'],
    ['sbtl', 'sbtl', 'sv'],
    ['sbtlfiexp', 'sbtlfiexp', 'en'],
    ['sbtlfiexp', 'sbtlfiexp', 'fi'],
    ['sbtlfiexp', 'sbtlfiexp', 'sv'],
    ['sbtlfirrex', 'sbtlfirrex', 'en'],
    ['sbtlfirrex', 'sbtlfirrex', 'fi'],
    ['sbtlfirrex', 'sbtlfirrex', 'sv'],
    ['ups', 'ups', 'en'],
    ['ups', 'ups', 'fi'],
    ['ups', 'ups', 'sv'],
    ['wolt', 'wolt', 'en'],
    ['wolt', 'wolt', 'fi'],
    ['wolt', 'wolt', 'sv'],
]);

// (new ParcelStrategy('kl.klgrp'))->generate('240425-012043'),
